---
- name: 'update and upgrade packages.' # sudo apt upgrade
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: remove unneeded dependencies  # auto remove sudo apt autoremove
  become: true
  apt:
    autoremove: yes
- name: install dependencies # install npm & node.js sudo apt install nodejs npm
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: install pm2 # install pm2 --> sudo npm pm2 -g
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes